import {StyleSheet, Dimensions} from 'react-native';
const style = StyleSheet.create({
    root: {
    flex: 1,
    backgroundColor: 'silver',
    justifyContent: 'center',
    alignItems: 'center',
    },

    Box1: {
    position: "absolute",
    left: 180.119140625,
    top: 0.0670166015625,
    width: 96,
    height: 531,
    borderRadius: null,
    backgroundColor: "",
    },

    Box2: {
    position: "absolute",
    left: 0,
    top: 0.09832763671875,
    width: 96,
    height: 531,
    borderRadius: null,
    backgroundColor: "",
    },
    
    Login_Title: {
    position: "absolute",
    left: 111,
    right: -221,
    top: 26,
    width: "auto",
    height: 82,
    color: "rgba(43, 43, 67, 1)",
    fontSize: 60,
    fontFamily: "Nunito",
    letterSpacing: -0.3999999985098839,
    fontStyle: "normal",
    fontWeight: 700,
    textAlign: "left",
    },
    
    Login_Title2: {
    position: "absolute",
    left: 15,
    right: -317,
    top: 108,
    width: "auto",
    height: 40,
    colsor: "rgba(84, 85, 99, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.3999999985098839,
    fontStyle: "normal",
    fontWeight: 400,
    textAlign: "left",
    },
    
    Email: {
    position: "absolute",
    left: 15,
    right: -17,
    top: 182,
    width: "auto",
    height: 16,
    color: "rgba(84, 85, 99, 1)",
    fontSize: 12,
    fontFamily: "Nunito",
    letterSpacing: -0.5,
    fontStyle: "normal",
    fontWeight: 600,
    textAlign: "left",
    },

    EmailBox: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 20,
    bottom: 20,
    width: "auto",
    height: "auto",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(199, 200, 210, 1)",
    backgroundColor: "",
    },

    EmailId: {
    position: "absolute",
    left: 27,
    right: -5,
    top: 214,
    bottom: -150,
    width: "auto",
    height: "auto",
    color: "rgba(78, 81, 86, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.3999999985098839,
    fontStyle: "normal",
    fontWeight: 400,
    textAlign: "left",
    },
 
    Password: {
    position: "absolute",
    left: 15,
    right: -17,
    top: 266,
    width: "auto",
    height: 16,
    color: "rgba(84, 85, 99, 1)",
    fontSize: 12,
    fontFamily: "Nunito",
    letterSpacing: -0.5,
    fontStyle: "normal",
    fontWeight: 600,
    textAlign: "left",
    },   

    _QLbz5e5YF3IRg67zCC49O: {
    position: "absolute",
    left: 15,
    right: 15,
    top: 182,
    width: "auto",
    height: 84,
    borderRadius: null,
    },

    PasswordBox: {
    position: "absolute",
    left: 15,
    right: -15,
    top: 286,
    bottom: -246,
    width: "auto",
    height: "auto",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(199, 200, 210, 1)",
    backgroundColor: "",
    },

    PasswordId: {
    position: "absolute",
    left: 12,
    right: 38,
    top: 32,
    bottom: 32,
    width: "auto",
    height: "auto",
    color: "rgba(78, 81, 86, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.3999999985098839,
    fontStyle: "normal",
    fontWeight: 400,
    textAlign: "left",
    },

    _P2mpY4tKQtdSKddkdr2lo: {
    position: "absolute",
    right: 12,
    top: 32,
    width: 20,
    height: 20,
    borderRadius: null,
    },

    position: "absolute",
    left: 0,
    right: -2,
    top: 0,
    width: "auto",
    height: 16,
    color: "rgba(84, 85, 99, 1)",
    fontSize: 12,
    fontFamily: "Nunito",
    letterSpacing: -0.5,
    fontStyle: "normal",
    fontWeight: 600,
    textAlign: "left",

    _DIpWhjVA6jm8YbmsTqD8d: {
    position: "absolute",
    left: 15,
    right: 15,
    top: 266,
    width: "auto",
    height: 84,
    borderRadius: null,
    },

    _ApIQsvszDnFKpNpnlW_7B: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "rgba(199, 200, 210, 1)",
    backgroundColor: "",
    },

    _XaBdw_mePQGtxuHUaFCtF: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 20,
    height: 20,
    borderRadius: null,
    },
  
    Keepme: {
    position: "absolute",
    left: 32,
    right: -2,
    top: 0,
    bottom: 0,
    width: "auto",
    height: "auto",
    color: "rgba(43, 43, 67, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.3999999985098839,
    fontStyle: "normal",
    fontWeight: 400,
    textAlign: "left",
    },

    _yZE4xEqEMFpYuwTIFzVjJ: {
    position: "absolute",
    left: 21,
    right: 9,
    top: 356,
    width: "auto",
    height: 20,
    borderRadius: null,
    },

    LoginButtonst: {
    flexBasis: 0,
    flexGrow: 1,
    width: "auto",
    height: 20,
    color: "rgba(255, 255, 255, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.19999998807907104,
    fontStyle: "normal",
    fontWeight: 700,
    textAlign: "center",
    },

    LoginButton: {
    position: "absolute",
    left: 15,
    right: 15,
    top: 422,
    width: "auto",
    height: "auto",
    display: "flex",
    row: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 12,
    paddingRight: 16,
    paddingBottom: 12,
    paddingLeft: 16,
    borderRadius: 8,
    backgroundColor: "rgba(78, 81, 86, 1)",
    },

    Forgot: {
    flexBasis: 0,
    flexGrow: 1,
    width: "auto",
    height: 20,
    color: "rgba(130, 130, 130, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.19999998807907104,
    fontStyle: "normal",
    fontWeight: 700,
    textAlign: "center",
    },

    ForgotBox: {
    position: "absolute",
    left: 15,
    right: 15,
    top: 466,
    width: "auto",
    height: "auto",
    display: "flex",
    row: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 12,
    paddingRight: 16,
    paddingBottom: 12,
    paddingLeft: 16,
    borderRadius: null,
    backgroundColor: "rgba(255, 255, 255, 0)",
    },
    
    Account: {
    position: "absolute",
    left: 21,
    right: -311,
    top: 570,
    width: "auto",
    height: 20,
    color: "rgba(84, 85, 99, 1)",
    fontSize: 14,
    fontFamily: "Nunito",
    letterSpacing: -0.3999999985098839,
    fontStyle: "normal",
    fontWeight: 400,
    textAlign: "center",
    },

    _S2as7wVOzMUrTELDteSHL: {
    position: "absolute",
    left: 91,
    top: 516,
    width: 40,
    height: 40,
    borderRadius: 400,
    backgroundColor: "rgba(78, 81, 86, 1)",
    },


    _QXUAPi__ITxH5Y7l_NbDB: {
    position: "absolute",
    left: 146,
    top: 516,
    width: 40,
    height: 40,
    borderRadius: 400,
    backgroundColor: "rgba(78, 81, 86, 1)",
    },

    position: "absolute",
    left: 8,
    top: 8,
    position: "absolute",
    left: 14,
    top: 14,
    position: "absolute",
    left: 25,
    top: 12,

    _C48fgahfPz6nay8275UNL: {
    position: "absolute",
    left: 201,
    top: 517,
    width: 40,
    height: 40,
    borderRadius: 400,
    backgroundColor: "rgba(78, 81, 86, 1)",
    },

    position: "absolute",
    left: 8,
    top: 12,

    _fCQuwqggtkaMyMct3wzdy: {
    position: "absolute",
    left: 251,
    top: 516,
    width: 40,
    height: 40,
    borderRadius: 400,
    backgroundColor: "rgba(78, 81, 86, 1)",
    },

    _1: {
    position: "relative",
    width: Dimensions.get("window").width,
    height: 640,
    backgroundColor: "rgba(255, 255, 255, 1)",
    },
    
    })
    
export default style;